import { FileText, AlertTriangle, ShieldCheck } from "lucide-react";

export default function Terms() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-sky-50 via-white to-emerald-50 py-16 px-6">
      <div className="max-w-4xl mx-auto bg-white rounded-3xl shadow-xl border p-10">

        <div className="text-center mb-10">
          <FileText className="w-16 h-16 mx-auto text-blue-600 mb-4" />
          <h1 className="text-4xl font-bold text-slate-800">
            Terms of Service
          </h1>
          <p className="text-slate-500 mt-2">
            Last Updated: July 2026
          </p>
        </div>

        <section className="space-y-6 text-slate-600">

          <div>
            <h2 className="text-2xl font-semibold text-slate-800 mb-2">
              Acceptance of Terms
            </h2>

            <p>
              By accessing Climate Guardian AI, you agree to comply with these
              Terms of Service and all applicable laws.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-slate-800 mb-2">
              AI Recommendations
            </h2>

            <p>
              Climate insights generated by AI are intended for informational
              purposes only and should not replace official weather warnings or
              emergency advisories.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-slate-800 mb-2">
              Acceptable Use
            </h2>

            <ul className="list-disc ml-6 space-y-2">
              <li>No unauthorized access.</li>
              <li>No misuse of APIs.</li>
              <li>No malicious activity.</li>
              <li>Respect platform limitations.</li>
            </ul>
          </div>

          <div className="flex gap-3">
            <ShieldCheck className="text-green-600 mt-1" />
            <p>
              We reserve the right to update or modify these terms at any time.
            </p>
          </div>

          <div className="flex gap-3">
            <AlertTriangle className="text-orange-500 mt-1" />
            <p>
              Climate Guardian AI is not liable for decisions made solely on
              AI-generated recommendations.
            </p>
          </div>

        </section>

      </div>
    </div>
  );
}